name: Criar App Android (Login Google)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pegar arquivos do GitHub
        uses: actions/checkout@v4

      - name: 2. Preparar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3. Criar Chave de Segurança do Aplicativo
        run: keytool -genkeypair -v -keystore android.keystore -alias android -keyalg RSA -keysize 2048 -validity 10000 -storepass senha123 -keypass senha123 -dname "CN=Album,O=Album,C=BR"

      - name: 4. Gerar Configurações do App
        run: |
          cat <<EOF > twa-manifest.json
          {
            "packageId": "com.arthur.album2026",
            "host": "arthurmatassoli.github.io",
            "name": "Álbum 2026",
            "launcherName": "Álbum 2026",
            "display": "standalone",
            "themeColor": "#125b34",
            "navigationColor": "#ffffff",
            "backgroundColor": "#ffffff",
            "startUrl": "/album-copa-2026/",
            "iconUrl": "https://www.pwabuilder.com/assets/icons/icon_512.png",
            "maskableIconUrl": "https://www.pwabuilder.com/assets/icons/icon_512.png",
            "signingKey": {
              "path": "android.keystore",
              "alias": "android"
            },
            "appVersionCode": 1,
            "appVersionName": "1.0",
            "generatorApp": "bubblewrap-cli",
            "webManifestUrl": "https://arthurmatassoli.github.io/album-copa-2026/manifest.json",
            "fallbackType": "customtabs",
            "features": {}
          }
          EOF

      - name: 5. Construir o Aplicativo Final (Usando Docker Oficial do Google)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workspace" -w "/workspace" ghcr.io/googlechromelabs/bubblewrap:latest update --skipVersionUpgrade
          docker run --rm -v "${{ github.workspace }}:/workspace" -w "/workspace" ghcr.io/googlechromelabs/bubblewrap:latest build --keyPassword=senha123 --keystorePassword=senha123

      - name: 6. Salvar o .APK para Download
